# Generated by Django 5.0.1 on 2024-01-03 10:00

import django.db.models.deletion
import sns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('header_image', models.ImageField(upload_to=sns.models.media_save_path)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=160)),
                ('location', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('profile_image', models.ImageField(upload_to=sns.models.media_save_path)),
                ('header_image', models.ImageField(upload_to=sns.models.media_save_path)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280)),
                ('image', models.ImageField(upload_to=sns.models.media_save_path)),
                ('quote_tweet_id', models.CharField(default=0, max_length=15)),
                ('tweeted_at', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.tweet')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.user')),
            ],
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.tweet')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.user')),
            ],
        ),
        migrations.CreateModel(
            name='ListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.list')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.user')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.user'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.tweet')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.user')),
            ],
        ),
        migrations.CreateModel(
            name='FollowList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.list')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.user')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='sns.user')),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='sns.user')),
            ],
        ),
    ]
