# Generated by Django 5.0.1 on 2024-01-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_alter_list_description_alter_list_header_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='quote_tweet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='sns.tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='sns.tweet'),
        ),
    ]
